import sqlite3

# Connect to database
conn = sqlite3.connect('anime.db')
cursor = conn.cursor()

# Your anime list

anime_list = [
    "Chainsaw Man",
    "Tokyo Revenger",
    "Tom 100 Bucket list of the dead",
    "The girl I like forgot her Glasses",
    "Liar Liar",
    "The 100 Gf who Really Really loves you",
    "Narnto",
    "Classroom of the elite",
    "Amagi Brilliant Park",
    "Amagi SS",
    "The Detective is Already Dead",
    "Re Zero",
    "Banished from the Hero Party",
    "The Eminence of Shadow",
    "Babylon",
    "The future Diary",
    "The Aristocrats",
    "Solo Levelling",
    "Magic a Mushle",
    "Lycoriss Recoil",
    "Bochi Rock",
    "I got cheat skill in another world",
    "Lookism",
    "Chained Solider",
    "The tales of wedding Rings",
    "Love election& chockolate",
    "The Dreaming Boy is Realist",
    "The time I got reincarted as a slime",
    "The hidden dungeo only I can enter",
    "7 time loop",
    "Myramid color phantom",
    "Do you love ur mo",
    "My one hit kill sis",
    "Makemine",
    "Frieren",
    "I got a cheat skill in another",
    "Little monster",
    "Vermeil in gold",
    "Bockhi the rock",
    "Chronicles of aristocrat reborn in another world",
    "Osamake",
    "Saekano",
    "Loving Yamada kun al 1999",
    "The cafe terrace and its goddess",
    "When supernatural battle becomes common place",
    "Konosuba",
    "Fruit Basket",
    "A galaxy next door",
    "Vinland Saga",
    "Swort art online",
    "Atri my dear moments",
    "Fate",
    "The strongest magician in demon kings army",
    "I am the villiances so I am faming the final boss",
    "Diabolic Lover",
    "Food wars",
    "The misfit of demon king academy",
    "Arifureta",
    "Mieruko chan",
    "A nobody's way to exploration hero",
    "The case study of vanitas",
    "Oreimo my little what",
    "Undefeated Bahmut chronicles",
    "V-tuber legend",
    "Wind breaker",
    "Tokyo revenger",
    "Saint Cecilia",
    "Steins Gate",
    "We never learn: Bokuben",
    "Eromanga Sensei",
    "Hensuki",
    "No longer allowed in another world",
    "Love is indivisible by twins",
    "2.5 dimentional seduction",
    "Re life",
    "Welcome to nhk",
    "The magical girl -evil lieutenant",
    "Dask maiden of Amnesia",
    "Fuuka",
    "Overload",
    "Oregairu",
    "Negative positive angler",
    "Mob physce 100",
    "Was never a",
    "And you thought there girl online",
    "Cupids chocklate",
    "Onimai",
    "Million Aurthur",
    "Blood C",
    "Hokeigo girls are super cute",
    "Infinite saratos",
    "Studio appartment god lightning",
    "So i can't play h",
    "Yukuza Fiance",
    "Hazbin hotel",
    "365 days to wedding",
    "You are my servant",
    "Amagami Sister",
    "Mecha Ude",
    "Love Tryant",
    "The ice guy a his cool female colleague",
    "Scissors seven",
    "Danmachi",
    "Can boy girl freindship survive",
    "The super cube",
    "To be herox",
    "Summer Pocket",
    "Takamine san",
    "Isekai Ojisan",
    "Headhunted to another world",
    "Medaka kuroiwa",
    "The beggining after the end"
]

# Update user_id to 3 for these titles
for anime in anime_list:
    cursor.execute('UPDATE anime SET rating = 0.0 WHERE title = ?', (anime,))

# Commit and close
conn.commit()
conn.close()